</sys/src/ape/config
OS=0568qv
all:
	pcc -c getopt.c
	pcc -c infinfo.c
	pcc -c infodump.c
	pcc -c showdict.c
	pcc -c showhead.c
	pcc -c showobj.c
	pcc -c showverb.c
	pcc -c -D_POSIX_SOURCE symbols.c
	pcc -c txd.c
	pcc -c txio.c
	pcc -o pix2gif pix2gif.c
	pcc -o check check.c
	pcc -o infodump infodump.$O showhead.$O showdict.$O showobj.$O showverb.$O txio.$O infinfo.$O symbols.$O
	pcc -o txd txd.$O txio.$O showverb.$O infinfo.$O symbols.$O showobj.$O
install:
	mk
	cp infodump /$objtype/bin
	cp txd /$objtype/bin
	cp pix2gif /$objtype/bin
clean:
	rm -f *.[$OS] [$OS].out y.tab.? lex.yy.c y.debug y.output $TARG $CLEANFILES
	rm infodump
	rm txd
	rm pix2gif
	rm check
