Abbreviate ". ";
Abbreviate ", ";
Abbreviate "STATIC_mscp_";
Abbreviate " the ";
Abbreviate "Chesspiece_";
Abbreviate "| | | |";
Abbreviate "You";
Abbreviate "The";
Abbreviate "+-+-+-+-+";
Abbreviate "ing";
Abbreviate "move";
Abbreviate "CONSTANT_";
Abbreviate ".^^~";
Abbreviate "playe";
Abbreviate "Like a modern";
Abbreviate "and";
Abbreviate " that";
Abbreviate "ece";
Abbreviate "ou can";
Abbreviate " chess";
Abbreviate " thi";
Abbreviate "STATIC_";
Abbreviate " ma";
Abbreviate " in";
Abbreviate " of";
Abbreviate " gam";
Abbreviate " gen";
Abbreviate " not";
Abbreviate " pi";
Abbreviate " wh";
Abbreviate " on";
Abbreviate " for";
Abbreviate "lay";
Abbreviate "board";
Abbreviate "That";
Abbreviate "Chess";
Abbreviate " their";
Abbreviate " want";
Abbreviate " ta";
Abbreviate "over";
Abbreviate " squar";
Abbreviate " is";
Abbreviate " from";
Abbreviate " diagonally";
Abbreviate "**]";
Abbreviate " number";
Abbreviate " was";
Abbreviate " wit";
Abbreviate " si";
Abbreviate " someth";
Abbreviate " point";
Abbreviate "Silicon Castles";
Abbreviate "ther";
Abbreviate " to ";
Abbreviate "s a";
Abbreviate "game";
Abbreviate "che";
Abbreviate "for";
Abbreviate "tion";
Abbreviate "you";
Abbreviate "ter";
Abbreviate "mscp_";
Abbreviate "General";
Abbreviate "can'";
