</sys/src/ape/config
OS=0568qv
all:
   pcc -c src/common/*.c
   pcc -c src/dumb/*.c
   pcc -o frotz *.$O
install:
	mk
	cp frotz /$objtype/bin
clean:
   rm -f *.[$OS] [$OS].out y.tab.? lex.yy.c y.debug y.output $TARG $CLEANFILES
   rm frotz
